name: Static Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci-environment
      - name: Run unit tests
        shell: bash
        run: npm run test
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci-environment
      - name: Run linter
        shell: bash
        run: npm run lint
